{{- if .Values.argocd.enabled }}
{{- include "mongo.validate" . -}}
{{- include "mongo.validateBackupConfig" . -}}
{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.secretDatabase.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Dictionary
data:
{{- if and .Values.backup.enabled (eq .Values.backup.provider "aws") }}
  backup-bucket: {{ .Values.backup.aws.bucket | b64enc | quote }}
  aws-region: {{ .Values.backup.aws.region | b64enc | quote }}
{{- end }}
{{- if and .Values.backup.enabled (eq .Values.backup.provider "gcp") }}
  backup-bucket: {{ .Values.backup.gcp.bucket | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
