{{- if .Values.argocd.enabled }}
{{- include "rabbitmq.validate" . -}}
{{- $conf := printf "listeners.tcp.default = %v" .Values.rabbitmq_conf.listeners_tcp_default }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Opaque
data:
  encoding: {{ "plain" | b64enc }}
  payload: {{ $conf | b64enc }}
{{- end }}
