{{- if .Values.argocd.enabled }}
{{- $dir := "/tmp" }}
{{- if and (hasKey .Values.sentinel "persistence") .Values.sentinel.persistence.enabled }}{{- $dir = "/etc/sentinel/data" }}{{- end }}
{{- $payload := printf "dir %s\nsentinel announce-hostnames yes\nsentinel resolve-hostnames yes\nsentinel down-after-milliseconds mymaster 5000\nsentinel failover-timeout mymaster 10000\nsentinel parallel-syncs mymaster 1" $dir }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.sentinelSecretConfig.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Opaque
data:
  encoding: {{ "plain" | b64enc }}
  payload: {{ $payload | b64enc }}
{{- end }}
