{{- if .Values.argocd.enabled }}
{{- include "redis.validateBackupConfig" . }}
{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretBackup.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Dictionary
data:
{{- if eq .Values.backup.provider "aws" }}
  backup-bucket: {{ .Values.backup.aws.bucket | b64enc }}
  aws-region: {{ .Values.backup.aws.region | b64enc }}
{{- end }}
{{- if eq .Values.backup.provider "gcp" }}
  backup-bucket: {{ .Values.backup.gcp.bucket | b64enc }}
{{- end }}
{{- end }}
{{- end }}
