{{- if .Values.argocd.enabled }}
{{- if and (hasKey .Values.redis "publicAccess") .Values.redis.publicAccess.enabled }}
apiVersion: cpln.io/v1
kind: domain
metadata:
  name: {{ .Values.redis.publicAccess.address }}
  namespace: {{ .Release.Namespace }}
org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
description: {{ .Values.redis.publicAccess.address }}
tags: {{- include "redis.tags" . | nindent 2 }}
spec:
  acceptAllHosts: false
  dnsMode: cname
  {{- if gt (.Values.redis.replicas | int) 0 }}
  ports:
    {{- range $i := until (int .Values.redis.replicas) }}
    - number: {{ add 6380 $i }}
      protocol: tcp
      routes:
        - port: {{ add 6380 $i }}
          prefix: /
          replica: {{ $i }}
          workloadLink: //gvc/{{ $.Values.global.cpln.gvc }}/workload/{{ include "redis.name" $ }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
