{{- if and .Values.argocd.enabled (or .Values.postgres.enabled .Values.postgresHA.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.db.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Dictionary
data:
  username: {{ .Values.postgres.credentials.username | b64enc }}
  password: {{ .Values.postgres.credentials.password | b64enc }}
  database: {{ .Values.postgres.credentials.database | b64enc }}
{{- end }}
