{{- if .Values.argocd.enabled }}
{{- $payload := include "keycloak.startupScript" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretStartup.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Opaque
data:
  encoding: {{ "plain" | b64enc }}
  payload: {{ $payload | b64enc }}
{{- end }}
