{{- if .Values.argocd.enabled }}
apiVersion: cpln.io/v1
kind: identity
metadata:
  name: {{ include "keycloak.identity.name" . }}
  namespace: {{ .Release.Namespace }}
org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
description: Keycloak workload identity
gvc: {{ .Values.global.cpln.gvc }}
tags: {{- include "keycloak.tags" . | nindent 4 }}
{{- end }}
