{{- if .Values.argocd.enabled }}
apiVersion: cpln.io/v1
kind: policy
metadata:
  name: {{ include "nginx.policy.name" . }}
  namespace: {{ .Release.Namespace }}
org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
description: Nginx policy
tags: {{- include "nginx.tags" . | nindent 2 }}
bindings:
  - permissions:
      - reveal
    principalLinks:
      - //gvc/{{ .Values.global.cpln.gvc }}/identity/{{ include "nginx.identity.name" . }}
targetKind: secret
targetLinks:
  - //secret/{{ include "nginx.secretConfig.name" . }}
{{- end }}
