{{- if .Values.argocd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.secretConfig.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cpln.io/org: {{ required "argocd.org is required when argocd.enabled is true" .Values.argocd.org }}
  labels:
    app.kubernetes.io/managed-by: cpln-operator
type: Opaque
data:
  encoding: {{ "plain" | b64enc }}
  payload: {{ tpl (.Files.Get "files/_nginxConf.txt") . | b64enc }}
{{- end }}
